language: node_js
node_js:
  - "8"
addons:
  code_climate:
    repo_token: d57db4426d9cd5567446cf1057c2a26de391c6686f4fe180b3df9dfce3408b0c
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
  - yarn ng test
before_script:
  - cd client
  - npm i
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
